### ISSUE TITLE
Cannot register

### ISSUE THREAD

**Issue by crocofied** [papra-hq/papra#245]
### Describe the bug

If i try to register on the fresh installed Papra instance i get the error: Invalid callbackURL
And in the console logs:
`POST https://docs.mydomain.cloud/api/auth/sign-up/email 403 (Forbidden)`

### What happened?

I cannot register a user account with error

### System information

Cloud VPS managed through Coolify

My Docker Compose:
```
services:
  papra:
    container_name: papra
    image: 'ghcr.io/papra-hq/papra:latest'
    restart: unless-stopped
    ports:
      - '1221:1221'
    volumes:
      - papra:/app/app-data

volumes:
  papra:
```

### Where did you encounter the bug?

A self hosted instance

**Comment by nekonora** [comment]
Same here `api/auth/sign-up/email:1 Failed to load resource: the server responded with a status of 403 ()` and `Invalid callbackURL` in UI.

Same docker config as the user above, but I deployed Papra on an Unraid machine, access through an nginx reverse proxy

**Comment by CorentinTh** [comment]
Hi @crocofied and @nekonora

It looks like you need to set the `CLIENT_BASE_URL=https://your-instance.tld` env variable

**Comment by crocofied** [comment]
Hey @CorentinTh ,

I just added the 3 env vars:
```yaml
services:
  papra:
    container_name: papra
    image: 'ghcr.io/papra-hq/papra:latest'
    restart: unless-stopped
    ports:
      - '1221:1221'
    environment:
      CLIENT_BASE_URL: "https://docs.mydomain.cloud"
      CLIENT_OAUTH_REDIRECT_URL: "https://docs.mydomain.cloud/confirm"
      SERVER_BASE_URL: "https://docs.mydomain.cloud"
    volumes:
      - papra:/app/app-data

volumes:
  papra:

```

But now I am getting the error:
`Failed to create user`
`POST https://docs.mydomain.cloud/api/auth/sign-up/email 422 (Unprocessable Content)`

**Comment by crocofied** [comment]
I still have this bug

**Comment by CorentinTh** [comment]
@crocofied can you check and provide your server logs please? We won't be able to help you with just the client side error

**Comment by adriencarbonaro** [comment]
Hi, I had the same *"Invalid CallbackURL"* in my config. Solved it by adding the env vars `CLIENT_BASE_URL`, `SERVER_BASE_URL` and `CLIENT_OAUTH_REDIRECT_URL`.
It should probably be mentionned early in the docker compose documentation, because the `compose.yml` file itself is not enough to use the app.

**Comment by lukewowo** [comment]
To add to this, you do not need a DNS name to get this to work; you can use local IP addresses if required.

I also added SERVER_CORS_ORIGIN and TRUSTED_ORIGINS

```
services:
  papra:
    container_name: papra
    image: ghcr.io/papra-hq/papra:latest
    restart: unless-stopped
    ports:
      - "1221:1221"
    volumes:
      - ./app-data:/app/app-data
    user: "1000:1000"
    environment:
      CLIENT_BASE_URL: "http://192.168.1.2:1221"
      CLIENT_OAUTH_REDIRECT_URL: "http://192.168.1.2:1221/confirm"
      SERVER_BASE_URL: "http://192.168.1.2:1221"
      TRUSTED_ORIGINS: "http://192.168.1.2:1221"
      SERVER_CORS_ORIGINS: "http://192.168.1.2:1221"
```
