### ISSUE TITLE
Container first time setup restarts continuously and can't connect to DB

### ISSUE THREAD

**Issue by gabeklavans** [papra-hq/papra#329]
### Describe the bug

Running this container for the first time on my system, I kept getting the following error and continual restarts in the container logs:

```
.env not found. Continuing without it.
.env not found. Continuing without it.
/app/node_modules/.pnpm/libsql@0.4.7/node_modules/libsql/index.js:83
      this.db = databaseOpen(path, authToken, encryptionCipher, encryptionKey);
                ^

Error: ConnectionFailed("Unable to open connection to local database ./app-data/db/db.sqlite: 14")
    at new Database (/app/node_modules/.pnpm/libsql@0.4.7/node_modules/libsql/index.js:83:17)
    at _createClient (file:///app/node_modules/.pnpm/@libsql+client@0.14.0/node_modules/@libsql/client/lib-esm/sqlite3.js:47:16)
    at _createClient (file:///app/node_modules/.pnpm/@libsql+client@0.14.0/node_modules/@libsql/client/lib-esm/node.js:21:16)
    at createClient (file:///app/node_modules/.pnpm/@libsql+client@0.14.0/node_modules/@libsql/client/lib-esm/node.js:11:12)
    at setupDatabase (/app/src/modules/app/database/database.ts:15:18)
    at <anonymous> (/app/src/scripts/commons/run-script.ts:26:30) {
  code: ''
}
```

I do use podman rootless with SELinux enabled but I believe I have all my permissions set up properly. This is evidenced by the fact that if I manually create this `db.sqlite` on the host system in the expected location in the volume mount, then container app setup proceeds seemingly successfully.

### What happened?

I expected to just run the basic docker compose provided by the documentation and have an auto-initialized papra setup.

### System information

```
OS: Fedora CoreOS 42.20250512.3.0 (uCore HCI) x86_64
Host: H110N
Kernel: Linux 6.14.5-300.fc42.x86_64
Shell: zsh 5.9
CPU: Intel(R) Core(TM) i5-6500 (4) @ 3.60 GHz
GPU: AMD Radeon RX 580 Series [Discrete]
Memory: 6.60 GiB / 31.29 GiB (21%)
```

my compose file:
```
services:
  papra:
    image: ghcr.io/papra-hq/papra:latest
    container_name: papra
    restart: unless-stopped
    ports:
      - 1221:1221
    environment:
      - AUTH_SECRET=$AUTH_SECRET
      - CLIENT_BASE_URL=<>
      - SERVER_BASE_URL=<>
      - INGESTION_FOLDER_IS_ENABLED=true
    volumes:
      - ~/elysium/appdata/papra/data:/app/app-data:Z
      - ~/tartarus/documents/ingestion:/app/ingestion:z
    user: 0:0 # simplify user namespace permissions, but I also tried mapped to my host ID with 1000:1000
```

### Where did you encounter the bug?

A self hosted instance
