### ISSUE TITLE
Can't register on fresh instance

### ISSUE THREAD

**Issue by I-Would-Like-To-Report-A-Bug-Please** [papra-hq/papra#342]
### Describe the bug

Using this docker-compose:
```yaml
services:
  papra:
    image: ghcr.io/papra-hq/papra:latest
    container_name: papra
    restart: unless-stopped
    ports:
      - 1221:1221
    environment:
      - AUTH_SECRET=7DoTupNVzXxaSSmaGRF7tgpoaWh3WWNo8fmc2ySyieytcIdl
      - CLIENT_BASE_URL=http://192.168.0.111:1221
      - SERVER_BASE_URL=http://192.168.0.111:1221
      - INGESTION_FOLDER_IS_ENABLED=true
    volumes:
      - /home/papra/app-data:/app/app-data
      - /home/papra/ingestion:/app/ingestion
    user: 1000:1000
```

### What happened?

When trying to register I am getting this:

![Image](https://github.com/user-attachments/assets/e64ddb5f-8cec-4d91-8101-a07681aa8064)

In the logs I can't see anything relevant:
```
{"level":"error","message":"Password is too short","timestampMs":1749646043159,"namespace":"auth","data":{"requestId":"req_aay582bok29kds3o6wkrzymx"}}
{"level":"info","message":"Request completed","timestampMs":1749646043160,"namespace":"app","data":{"requestId":"req_aay582bok29kds3o6wkrzymx","status":400,"method":"POST","path":"/api/auth/sign-up/email","routePath":"/api/auth/*","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0","durationMs":2}}
```
(password too short is before I updated password to required length)

in sqlite database, if I do `select * from users` there's nothing.

### System information

docker

### Where did you encounter the bug?

A self hosted instance

**Comment by rcjcarr** [comment]
Same problem for me...
```yml
services:
  papra:
    container_name: papra
    image: ghcr.io/papra-hq/papra:latest
    restart: unless-stopped
    ports:
      - "1221:1221"
    volumes:
      - ./app-data:/app/app-data
    environment:
      - AUTH_SECRET=7DoTpuNVzXxaSSmaGRF7tgpoahW3WWNo8fmc2SyyieytIcdl
      - CLIENT_BASE_URL=http://192.168.1.51:1221
      - SERVER_BASE_URL=http://192.168.1.51:1221
      - INGESTION_FOLDER_IS_ENABLED=false
  ```
