### ISSUE TITLE
Custom OAuth instructions don't work

### ISSUE THREAD

**Issue by dymdipii** [papra-hq/papra#361]
I'm following the custom [OAuth guide](https://docs.papra.app/guides/setup-custom-oauth2-providers/) but the custom provider config isn't accepted in my .env file. 

My docker compose config:

```
services:
  papra:
    image: corentinth/papra:latest
    container_name: papra
    restart: unless-stopped
    ports:
      - 1221:1221
    environment:
      - AUTH_SECRET=<redacted>
      - CLIENT_BASE_URL=https://papra.<redacted>
      - SERVER_BASE_URL=https://papra.<redacted>
      - CLIENT_OAUTH_REDIRECT_URL=https://papra.<redacted>/confirm
    volumes:
      - ./app-data:/app/app-data
    user: 1000:1000
```

My .env file:

```
AUTH_PROVIDERS_CUSTOMS='[
  {
    "providerId": "authentik",
    "providerName": "authentik",
    "providerIconUrl": "https://api.iconify.design/tabler:login-2.svg",
    "clientId": "<redacted>",
    "clientSecret": "<redacted>",
    "type": "oidc",
    "discoveryUrl": "https://authentik.<redacted>/application/o/papra/.well-known/openid-configuration",
    "scopes": ["openid", "profile", "email"]
  }
]'
```

I'm getting the following error:

![Image](https://github.com/user-attachments/assets/8853dac3-259a-4345-b3f0-4f2587cc368d)

I can modify the .env file to:

```
AUTH_PROVIDERS_CUSTOMS='[{
    "providerId": "authentik",
    "providerName": "authentik",
    "providerIconUrl": "https://api.iconify.design/tabler:login-2.svg",
    "clientId": "<redacted>",
    "clientSecret": "<redacted>",
    "type": "oidc",
    "discoveryUrl": "https://authentik.<redacted>/application/o/papra/.well-known/openid-configuration",
    "scopes": ["openid", "profile", "email"]}]'
```

And it's accepted. However, the OAuth login button doesn't appear on the papra login screen:

![Image](https://github.com/user-attachments/assets/b161c9ab-b73c-4929-a1a4-d48091f7afbc)
